export const ITENS_VEICULO = [
  { id: "retrovisor_direito", label: "Retrovisor direito", grupo: "Exterior" },
  { id: "retrovisor_esquerdo", label: "Retrovisor esquerdo", grupo: "Exterior" },
  { id: "retrovisor_interno", label: "Retrovisor interno", grupo: "Exterior" },
  { id: "farois", label: "Faróis", grupo: "Exterior" },
  { id: "farol_milha", label: "Farol de milha", grupo: "Exterior" },
  { id: "radio", label: "Rádio", grupo: "Acessórios" },
  { id: "alto_falante", label: "Alto-falante", grupo: "Acessórios" },
  { id: "antena", label: "Antena", grupo: "Acessórios" },
  { id: "painel_console", label: "Painel / console", grupo: "Acessórios" },
  { id: "tapete", label: "Tapetes", grupo: "Acessórios" },
  { id: "tampao_traseiro", label: "Tampão traseiro", grupo: "Acessórios" },
  { id: "documentos", label: "Documentos", grupo: "Acessórios" },
  { id: "banco_dianteiro_direito", label: "Banco dianteiro direito", grupo: "Interior" },
  { id: "banco_dianteiro_esquerdo", label: "Banco dianteiro esquerdo", grupo: "Interior" },
  { id: "banco_traseiro", label: "Banco traseiro", grupo: "Interior" },
  { id: "alarme", label: "Alarme", grupo: "Interior" },
  { id: "ar_condicionado", label: "Ar-condicionado", grupo: "Interior" },
  { id: "roda_liga_leve", label: "Roda de liga leve", grupo: "Rodas e pneus" },
  { id: "roda_aco", label: "Roda de aço", grupo: "Rodas e pneus" },
  { id: "calotas", label: "Calotas", grupo: "Rodas e pneus" },
  { id: "pneus", label: "Pneus", grupo: "Rodas e pneus" },
  { id: "estepe", label: "Estepe", grupo: "Rodas e pneus" },
  { id: "macaco", label: "Macaco", grupo: "Rodas e pneus" },
  { id: "chave_roda", label: "Chave de roda", grupo: "Rodas e pneus" },
  { id: "suspensao", label: "Suspensão", grupo: "Mecânica e segurança" },
  { id: "triangulo", label: "Triângulo", grupo: "Mecânica e segurança" },
  { id: "extintor", label: "Extintor", grupo: "Mecânica e segurança" },
  { id: "manual", label: "Manual", grupo: "Documentos e chaves" },
  { id: "chave_veiculo", label: "Chave do veículo", grupo: "Documentos e chaves" },
  { id: "chave_reserva", label: "Chave reserva", grupo: "Documentos e chaves" },
  { id: "tacografo", label: "Tacógrafo", grupo: "Documentos e chaves" },
] as const;

export type ChecklistItens = Record<string, boolean>;
